name: GitHub metrics
on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches: "master"
  workflow_dispatch:
jobs:

  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

      - name: Personal metrics
        uses: Harry-Yep/metrics@master
        with:
          filename: img/metrics/metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, repositories"
          plugin_lines: yes
          plugin_isocalendar: yes
          config_timezone: Europe/London
          config_order: base.header, isocalendar, base.repositories
          config_padding: 10%
          use_prebuilt_image: master 
          
      - name: Personal metrics (additional)
        uses: Harry-Yep/metrics@master
        with:
          filename: img/metrics/metrics.additional.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_skipped: lowlighter
          plugin_stargazers: yes
          plugin_stars: yes
          plugin_stars_limit: 3
          config_timezone: Europe/London
          config_order: languages, pagespeed, habits, stargazers, stars
          use_prebuilt_image: master

      # Classic template with header and repositories sections
      - name: Classic template
        uses: Harry-Yep/metrics@master
        with:
          filename: img/metrics/metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, repositories"
          plugin_lines: yes
          plugins_errors_fatal: yes
          config_timezone: Europe/London
          use_prebuilt_image: master

      # Terminal template with header and metadata sections
      - name: Terminal template
        uses: Harry-Yep/metrics@master
        with:
          template: terminal
          filename: img/metrics/metrics.terminal.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, metadata"
          plugins_errors_fatal: yes
          config_timezone: Europe/London
          use_prebuilt_image: master

      # Google PageSpeed insight audits
      # Don't forget to update your GitHub profile with your website
      # Token is optional but advised
      - name: PageSpeed plugin
        uses: Harry-Yep/metrics@master
        with:
          filename: img/metrics/metrics.plugin.pagespeed.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugins_errors_fatal: yes
          config_timezone: Europe/London
          use_prebuilt_image: master

      # Google PageSpeed insight audits, with additional performance metrics displayed
      # Don't forget to update your GitHub profile with your website
      # Token is optional but advised
      - name: PageSpeed plugin (detailed)
        uses: Harry-Yep/metrics@master
        with:
          filename: img/metrics/metrics.plugin.pagespeed.detailed.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugins_errors_fatal: yes
          config_timezone: Europe/London
          use_prebuilt_image: master

      # Google PageSpeed insight audits, with an additional screenshot of your website
      # Don't forget to update your GitHub profile with your website
      # Token is optional but advised
      - name: PageSpeed plugin (screenshot)
        uses: Harry-Yep/metrics@master
        with:
          filename: img/metrics/metrics.plugin.pagespeed.screenshot.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_screenshot: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugins_errors_fatal: yes
          config_timezone: Europe/London
          use_prebuilt_image: master

      # Display coding habits and recent activity
      # Don't forget to setup timezone for accurate metrics
      - name: Habits plugin
        uses: Harry-Yep/metrics@master
        with:
          filename: img/metrics/metrics.plugin.habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugins_errors_fatal: yes
          config_timezone: Europe/London
          use_prebuilt_image: master

      # Display coding habits and recent activity (only facts section)
      # Don't forget to setup timezone for accurate metrics
      - name: Habits plugin (facts)
        uses: Harry-Yep/metrics@master
        with:
          filename: img/metrics/metrics.plugin.habits.facts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          plugins_errors_fatal: yes
          config_timezone: Europe/London
          use_prebuilt_image: master

      # Display coding habits and recent activity (only charts section)
      # Don't forget to setup timezone for accurate metrics
      - name: Habits plugin (charts)
        uses: Harry-Yep/metrics@master
        with:
          filename: img/metrics/metrics.plugin.habits.charts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugins_errors_fatal: yes
          config_timezone: Europe/London
          use_prebuilt_image: master

      # Display most used languages
      # You can ignore some languages and skip some repositories if you want
      - name: Languages plugin
        uses: Harry-Yep/metrics@master
        with:
          filename: img/metrics/metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_skipped: lowlighter
          plugins_errors_fatal: yes
          config_timezone: Europe/London
          use_prebuilt_image: master

      # Display ratio of open/closed/merged issues and pull requests 
      - name: Follow-up plugin
        uses: Harry-Yep/metrics@master
        with:
          filename: img/metrics/metrics.plugin.followup.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_followup: yes
          plugins_errors_fatal: yes
          config_timezone: Europe/London
          use_prebuilt_image: master

      # Display number of line changed
      # Note that :
      # - This is part of "repositories" section, so you need to enable it
      - name: Lines plugin
        uses: Harry-Yep/metrics@master
        with:
          filename: img/metrics/metrics.plugin.lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "repositories"
          plugin_lines: yes
          plugins_errors_fatal: yes
          config_timezone: Europe/London
          use_prebuilt_image: master

      # Display recent posts
      # Note that : 
      # - "plugin_posts_source" is required
      # - With "dev.to" as source, your GitHub username is directly used
      - name: Posts plugin
        uses: Harry-Yep/metrics@master
        with:
          filename: img/metrics/metrics.plugin.posts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_posts: yes
          plugin_posts_source: dev.to
          plugins_errors_fatal: yes
          config_timezone: Europe/London
          use_prebuilt_image: master

      # Display isometric calendar (180 days)
      - name: Isocalendar plugin
        uses: Harry-Yep/metrics@master
        with:
          filename: img/metrics/metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugins_errors_fatal: yes
          config_timezone: Europe/London
          use_prebuilt_image: master

      # Display isometric calendar (365 days)
      - name: Isocalendar plugin (full year)
        uses: Harry-Yep/metrics@master
        with:
          filename: img/metrics/metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugins_errors_fatal: yes
          config_timezone: Europe/London
          use_prebuilt_image: master

      # Display gists metrics
      - name: Gists plugin
        uses: Harry-Yep/metrics@master
        with:
          filename: img/metrics/metrics.plugin.gists.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_gists: yes
          plugins_errors_fatal: yes
          config_timezone: Europe/London
          use_prebuilt_image: master

      # Display starred topics (as labels)
      - name: Topics plugin
        uses: Harry-Yep/metrics@master
        with:
          filename: img/metrics/metrics.plugin.topics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 12
          plugins_errors_fatal: yes
          config_timezone: Europe/London
          use_prebuilt_image: master

      # Display starred topics (as icons)
      # Note that : 
      # - Only topics with an icon will be displayed (most of majors topics have one anyway)
      - name: Topics plugin (mastered)
        uses: Harry-Yep/metrics@master
        with:
          filename: img/metrics/metrics.plugin.topics.mastered.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_topics: yes
          plugin_topics_mode: mastered
          plugins_errors_fatal: yes
          config_timezone: Europe/London
          use_prebuilt_image: master
          
      # Display your stargazers evolutions
      - name: Stargazers plugin
        uses: Harry-Yep/metrics@master
        with:
          filename: img/metrics/metrics.plugin.stargazers.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_stargazers: yes
          plugins_errors_fatal: yes
          config_timezone: Europe/London
          use_prebuilt_image: master
          
      # Display your latest starred repositories
      - name: Stars plugin
        uses: Harry-Yep/metrics@master
        with:
          filename: img/metrics/metrics.plugin.stars.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 2
          plugins_errors_fatal: yes
          config_timezone: Europe/London
          use_prebuilt_image: master
          
      # Display recent activity metrics
      - name: Activity plugin
        uses: Harry-Yep/metrics@master
        with:
          filename: img/metrics/metrics.plugin.activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 4
          plugin_activity_days: 0
          plugin_activity_filter: push, issue, pr, release
          plugins_errors_fatal: yes
          config_timezone: Europe/London
          config_padding: 10%
          use_prebuilt_image: master

      # This is used to illustrate plugin errors : 
      # The "METRICS_TOKEN" does not contains the "public_repo" scope, which is required for "plugin_projects"
      # It will display an "Insufficient token rights" error
      - name: Plugin error example
        uses: Harry-Yep/metrics@master
        with:
          filename: img/metrics/metrics.plugin.error.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_projects: yes
          plugins_errors_fatal: no
          config_timezone: Europe/London
          use_prebuilt_image: master
          
      # Display followers and followed users
      # Note that : 
      # - To respect privacy of users (as their faces could be displayed on every fork of this repository and on lowlighter/metrics), 
      #   identicons option is used to hide their avatar, but you probably want to remove it if you use this plugin
      - name: People plugin (followers)
        uses: Harry-Yep/metrics@master
        with:
          filename: img/metrics/metrics.plugin.people.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_people: yes 
          plugin_people_identicons: yes
          plugins_errors_fatal: yes
          config_timezone: Europe/London
          use_prebuilt_image: master
          
      # Display followers and followed users (only followers)
      - name: People plugin (followers)
        uses: Harry-Yep/metrics@master
        with:
          filename: img/metrics/metrics.plugin.people.followers.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_people: yes 
          plugin_people_identicons: yes
          plugin_people_types: followers
          plugins_errors_fatal: yes
          config_timezone: Europe/London
          use_prebuilt_image: master

      # Display followers and followed users (only following)
      - name: People plugin (following)
        uses: Harry-Yep/metrics@master
        with:
          filename: img/metrics/metrics.plugin.people.following.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_people: yes 
          plugin_people_identicons: yes
          plugin_people_types: following
          plugins_errors_fatal: yes
          config_timezone: Europe/London 
          use_prebuilt_image: master
